create table finop_staging
( OP_DATE DATE
, AMOUNT VARCHAR2(4000 CHAR)
, BALANCE_ID NUMBER(2, 0) 
, CONTRACTOR_ID NUMBER 
, ACCOUNT_ID NUMBER(3, 0) 
, COMMENTS VARCHAR2(4000 CHAR) 
, OP_DIRECTION NUMBER(1, 0) 
, CURRENCY_ID NUMBER(1, 0) 
);